"""add ai_explanation

Revision ID: dfe94ae9c6a4
Revises: e6b4f9c3d2a5
Create Date: 2026-05-21 16:33:48.186427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe94ae9c6a4'
down_revision: Union[str, Sequence[str], None] = 'e6b4f9c3d2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('ai_explanation', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_logs', 'ai_explanation')
    # ### end Alembic commands ###
